name: Issue - Bug
description: Reporte de bugs
labels: ["type: bug"]
body:
  - type: textarea
    attributes:
      label: Descripcion del problema
    validations:
      required: true
  - type: input
    attributes:
      label: URL/Path Afectado
    validations:
      required: false
  - type: textarea
    attributes:
      label: Precondiciones
    validations:
      required: false
  - type: textarea
    attributes:
      label: Paso a paso
      value: |
        1. Ir a '...'
        2. Hacer click en '...'
        3. scrollear hasta '...'
        4. verificar error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Resultado esperado
    validations:
      required: true
  - type: textarea
    attributes:
      label: Evidencia (Screenshots)
    validations:
      required: false
  - type: textarea
    attributes:
      label: Info Adicional
      description: Agregar detalles adicionales del contexto/env que crea necesario.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Criticidad
      options:
        - Critica
        - Alta
        - Media
        - Baja
    validations:
      required: true  
  - type: dropdown
    attributes:
      label: Prioridad
      options:
        - Alta
        - Media
        - Baja
    validations:
      required: true
